// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_vdKr_XxlgRXpqyPwAIWh-8m956B8hk',
    appId: '1:654450089031:web:59032b21300e72fb01e562',
    messagingSenderId: '654450089031',
    projectId: 'myflutterapp-bdd77',
    authDomain: 'myflutterapp-bdd77.firebaseapp.com',
    storageBucket: 'myflutterapp-bdd77.appspot.com',
    measurementId: 'G-VW4TBML9G6',
    databaseURL: 'https://myflutterapp-bdd77-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHbfiwoxMSclm7BOTaxVCHeBBmjM_lBo',
    appId: '1:654450089031:android:8973993bd2b2968e01e562',
    messagingSenderId: '654450089031',
    projectId: 'myflutterapp-bdd77',
    storageBucket: 'myflutterapp-bdd77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZkhKIjtfvduY9ltzzJxstOiXN2gQOAA',
    appId: '1:654450089031:ios:cc9c8d33e1b0ef6a01e562',
    messagingSenderId: '654450089031',
    projectId: 'myflutterapp-bdd77',
    storageBucket: 'myflutterapp-bdd77.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZkhKIjtfvduY9ltzzJxstOiXN2gQOAA',
    appId: '1:654450089031:ios:cc9c8d33e1b0ef6a01e562',
    messagingSenderId: '654450089031',
    projectId: 'myflutterapp-bdd77',
    storageBucket: 'myflutterapp-bdd77.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4_vdKr_XxlgRXpqyPwAIWh-8m956B8hk',
    appId: '1:654450089031:web:2012d5f680e4503101e562',
    messagingSenderId: '654450089031',
    projectId: 'myflutterapp-bdd77',
    authDomain: 'myflutterapp-bdd77.firebaseapp.com',
    storageBucket: 'myflutterapp-bdd77.appspot.com',
    measurementId: 'G-PNKK1TF71X',
  );
}
